### ISSUE TITLE
первый экран

### ISSUE THREAD

**Issue by Edrick53** [kubikvest/api#10]
[ ]
сюда человек попадает по ссылке с лэндига в группе ВК (там сдержатся правила и предостережения)
1. вверху картинка логотип
2. ниже (серединка) описание квеста текст
3. внизу кнопка "играть" которая ведет на следующий экран
при нажатии на играть происходит авторизация в ВК в промежуточном окне

**Comment by iMega** [comment]
Перенеси в kubikvest/front

**Comment by iMega** [comment]
по UI писать на kubikvest/front

**Comment by iMega** [comment]
Перенес kubikvest/front#3
