### ISSUE TITLE
второй экран

### ISSUE THREAD

**Issue by Edrick53** [kubikvest/api#11]
авторизовался в ВК попал сюда
1. картинка
2. текстовое поле "вам надо подойти туда то туда то" (точки старта будут разные для каждого квеста, может быть и несколько точек, которые выпадают разные разным пользователям)
3. кнопка "я на месте" проверяет геопозицию, если верна то переход на следующий экран
если нет, то появляется текст "вы еще не на нужном месте, дойдите до точки старта и нажмите еще раз кнопку "я на месте"
прим. допустим компания из 6 чел. разделилась на три команды взяла один и тот же квест и решили посоревноваться, чтобы они не пересекались, надо их развести на старте, поэтому они получат разные точки старта.

**Comment by iMega** [comment]
по UI писать на kubikvest/front

**Comment by iMega** [comment]
Перенес kubikvest/front#4
