### ISSUE TITLE
третий экран основной где идет вся игра

### ISSUE THREAD

**Issue by Edrick53** [kubikvest/api#12]
пришел на точку старта проверил позицию все верно приходит первое задание.
1. картинка
2. заголовок "задание 1"
3. задание "текст"
4. кнопка "проверить ответ" тоже самое, проверяется геопозиция, если верна, пререход на второе задание, если нет появляется текст "подумайте еще, ваша геопозиция неверна"
5. текст "подсказка 1" рядом отсчет таймер 19:59 до того как она откроется, закончился таймер открывается "текст подсказки"
6. текст "подсказка 2" - тоже самое
7. ответ - тоже самое (пока так или иначе не дойдешь до нужной области которая загадана, следующего задания не получишь)

так 5 раз, 5 заданий, либо на одном странице, либо 5 экранов, тут не знаю как удобнее с точки зрения программирования.
прим. в дальнейшем, надо будет добавить кнопку "активировать подсказку", чтобы люди не ждали, а покупали ее, кто хочет на скорость и быстрее.

Короче, мне нужно, чтобы был скелет этого приложения и можно было вставить текст стартовых точек, заданий, подсказок, ответов и это все тыкалось, чтобы посмотреть как это все выглядит и протестировать.

**Comment by iMega** [comment]
Перенес kubikvest/front#5
