### ISSUE TITLE
я блондинко

### ISSUE THREAD

**Issue by pailik** [kubikvest/api#23]
из 
'Задание 0'
убрать
                'prompt' => [
                    20 => 'Первая подсказка',
                    40 => 'Вторая подсказка',
                    60 => 'Ответ',
                ],

**Comment by pailik** [comment]
убрать

sfsdfsdf

**Comment by iMega** [comment]
sfsdfsdf находится в kubikvest/front

**Comment by iMega** [comment]
не актуально
