### ISSUE TITLE
Смотрю в коде 3 задания, но их 5.

### ISSUE THREAD

**Issue by Edrick53** [kubikvest/api#29]
[
                'kvest'       => 1,
                'point'       => 3,
                'title' => 'Задание 3',
                'description' => 'Задание 3. Последнее задание',
                'coords' => [
                    'latitude'  => [0, 100],
                    'longitude' => [0, 100],
                ],
                'prompt' => [
                    20 => 'Первая подсказка',
                    40 => 'Вторая подсказка',
                    60 => 'Ответ',
Если только это не сокращение для тестирования, то должно быть 5 заданий.
- [x] Довернуть до 5ти заданий

**Comment by iMega** [comment]
Добавь сколько надо
